import React, { useState } from "react";
import { View, Text, StyleSheet, TouchableOpacity, Switch } from "react-native";
import QRCode from "react-native-qrcode-svg";
import { Shield, Eye, EyeOff, Copy } from "lucide-react-native";
import { borderRadius, colors, spacing, typography } from "../theme";
import * as Clipboard from "expo-clipboard";

interface ShareReceiptProps {
  txHash: string;
  description: string;
  amount: string;
  amountUsd: string;
  date: string;
  category?: string;
  isNotarized?: boolean;
  notarizationTx?: string;
  note?: string;
}

export function ShareReceipt({
  txHash,
  description,
  amount,
  amountUsd,
  date,
  category,
  isNotarized,
  notarizationTx,
  note,
}: ShareReceiptProps) {
  const [hideAmount, setHideAmount] = useState(false);
  const [showNote, setShowNote] = useState(false);
  const [copied, setCopied] = useState(false);

  const solscanUrl = `https://solscan.io/tx/${txHash}`;
  const shortHash = `${txHash.slice(0, 8)}...${txHash.slice(-8)}`;

  const handleCopy = async () => {
    await Clipboard.setStringAsync(txHash);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <View style={styles.card}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.logoRow}>
          <View style={styles.logoIcon}>
            <Text style={styles.logoText}>M</Text>
          </View>
          <Text style={styles.logoLabel}>Memo Receipt</Text>
        </View>
        {isNotarized && (
          <View style={styles.notarizedBadge}>
            <Shield size={12} stroke={colors.success} />
            <Text style={styles.notarizedText}>NOTARIZED</Text>
          </View>
        )}
      </View>

      <View style={styles.divider} />

      {/* Transaction info */}
      <View style={styles.section}>
        <Text style={styles.description}>{description}</Text>
        <Text style={styles.date}>{date}</Text>
      </View>

      {/* Amount */}
      <View style={styles.amountRow}>
        <View>
          <Text style={styles.amountLabel}>AMOUNT</Text>
          <Text style={styles.amount}>{hideAmount ? "••••••" : amountUsd}</Text>
          <Text style={styles.amountSol}>
            {hideAmount ? "•••• SOL" : amount}
          </Text>
        </View>
        <TouchableOpacity
          onPress={() => setHideAmount(!hideAmount)}
          style={styles.eyeButton}
        >
          {hideAmount ? (
            <EyeOff size={20} stroke={colors.textMuted} />
          ) : (
            <Eye size={20} stroke={colors.textMuted} />
          )}
        </TouchableOpacity>
      </View>

      {/* Meta rows */}
      <View style={styles.metaBox}>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Signature</Text>
          <TouchableOpacity style={styles.metaValueRow} onPress={handleCopy}>
            <Text style={styles.metaValue}>{shortHash}</Text>
            <Copy
              size={12}
              stroke={copied ? colors.success : colors.textMuted}
            />
          </TouchableOpacity>
        </View>

        {category && (
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Category</Text>
            <Text style={styles.metaValue}>{category}</Text>
          </View>
        )}

        {isNotarized && notarizationTx && (
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Notarization Tx</Text>
            <Text style={styles.metaValue}>
              {`${notarizationTx.slice(0, 6)}...${notarizationTx.slice(-6)}`}
            </Text>
          </View>
        )}
      </View>

      {/* Note toggle */}
      {note && (
        <View style={styles.noteToggleRow}>
          <Text style={styles.noteToggleLabel}>Show note</Text>
          <Switch
            value={showNote}
            onValueChange={setShowNote}
            trackColor={{ false: colors.border, true: colors.primary }}
            thumbColor={colors.textPrimary}
          />
        </View>
      )}

      {showNote && note && (
        <View style={styles.noteBox}>
          <Text style={styles.noteText}>{note}</Text>
        </View>
      )}

      <View style={styles.divider} />

      {/* QR Code */}
      <View style={styles.qrContainer}>
        <QRCode
          value={solscanUrl}
          size={140}
          color={colors.textPrimary}
          backgroundColor={colors.surface}
        />
        <Text style={styles.qrLabel}>Scan to verify on Solscan</Text>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated by Memo · memo.app</Text>
        <Text style={styles.footerText}>Powered by Solana</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.md,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  logoIcon: {
    width: 28,
    height: 28,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  logoText: {
    color: colors.textPrimary,
    fontSize: typography.md,
    fontWeight: "800",
  },
  logoLabel: {
    color: colors.textPrimary,
    fontSize: typography.md,
    fontWeight: "700",
  },
  notarizedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.success + "20",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.success + "40",
  },
  notarizedText: {
    color: colors.success,
    fontSize: typography.xs,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
  },
  section: {
    gap: spacing.xs,
  },
  description: {
    color: colors.textPrimary,
    fontSize: typography.lg,
    fontWeight: "700",
    lineHeight: 24,
  },
  date: {
    color: colors.textMuted,
    fontSize: typography.sm,
  },
  amountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  amountLabel: {
    color: colors.textMuted,
    fontSize: typography.xs,
    fontWeight: "600",
    letterSpacing: 1,
    marginBottom: spacing.xs,
  },
  amount: {
    color: colors.textPrimary,
    fontSize: typography.xxxl,
    fontWeight: "800",
  },
  amountSol: {
    color: colors.textSecondary,
    fontSize: typography.sm,
    marginTop: 2,
  },
  eyeButton: {
    padding: spacing.sm,
  },
  metaBox: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  metaLabel: {
    color: colors.textMuted,
    fontSize: typography.sm,
  },
  metaValue: {
    color: colors.textPrimary,
    fontSize: typography.sm,
    fontWeight: "500",
  },
  noteToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  noteToggleLabel: {
    color: colors.textSecondary,
    fontSize: typography.sm,
    fontWeight: "500",
  },
  noteBox: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
  },
  noteText: {
    color: colors.textSecondary,
    fontSize: typography.sm,
    fontStyle: "italic",
    lineHeight: 20,
  },
  qrContainer: {
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  qrLabel: {
    color: colors.textMuted,
    fontSize: typography.xs,
    textAlign: "center",
  },
  footer: {
    alignItems: "center",
    gap: spacing.xs,
  },
  footerText: {
    color: colors.textMuted,
    fontSize: typography.xs,
  },
});
